export enum ComponentIds {
    Input = "Revind-Input",
    InputLabel = "Revind-Input-Label",
    InputAddon = "Revind-Input-Addon",
    Button = "Revind-Button",
    ButtonGroup = "Revind-Button-Group",
    Checkbox = "Revind-Checkbox",
    Container = "Revind-Container",
    Hidden = "Revind-Hidden",
    Flex = "Revind-Flex",
    Portal = "Revind-Portal",
    Radio = "Revind-Radio",
    RadioGroup = "Revind-Radio-Group",
    Stack = "Revind-Stack",
    HStack = "Revind-HStack",
    VStack = "Revind-VStack",
    Text = "Revind-Text",
    Textarea = "Revind-Textarea",
}
